<?php
// module/Artist/view/artist/artist/delete.phtml:

$title = 'Delete artist';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($artist->first_name); ?>' '<?php echo $this->escapeHtml($artist->last_name); ?>' by
    '<?php echo $this->escapeHtml($artist->genre); ?>'
    '(<?php echo $this->escapeHtml($artist->year); ?>)'?
</p>
<?php
$url = $this->url('artist', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $artist->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>