<?php
// module/Artist/view/artist/artist/edit.phtml:

$title = 'Edit artist';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'artist',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('first_name'));
echo $this->formRow($form->get('last_name'));
echo $this->formRow($form->get('alias_name'));
echo $this->formRow($form->get('genre'));
echo $this->formRow($form->get('year'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();